import Head from 'next/head'
import { Fragment } from 'react'
import styles from '../styles/Homepage.module.css'
import Image from 'next/image'
import Hero from '../components/homepage/Hero'

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

    </Fragment>
  )
}
